### ISSUE TITLE
2 Col db in 1 Col td

### ISSUE THREAD

**Issue by senzlord** [syamsoul/laravel-datatable-ssp#1]
is there any way to get this ? 
So i want to take my voting coloumn and voting average for 1 label...

**Comment by senzlord** [comment]
```
$dt = [
            ['label'=>'ID Movie',   'db'=>'id',            'dt'=>0, 'formatter'=>function($obj){ return str_pad($obj['value'], 5, '0', STR_PAD_LEFT); }],
            ['label'=>'Name',       'db'=>'title',         'dt'=>1],
            ['label'=>'Genre ID',   'db'=>'genre_id',      'dt'=>2],
            ['label'=>'Popularity', 'db'=>'popularity',    'dt'=>3],
            ['label'=>'Voting',     'db'=>'vote_average',  'dt'=>4, 'formatter'=>function($obj){ return $obj['value']." / 10"; }],
            ['label'=>'Menu',       'db'=>'id',            'dt'=>5, 'formatter'=>function($obj){
                $btns = [
                    '<button type="button" data-toggle="modal" data-target="#EmbedVideos"
                    class="btn btn-primary" data-id="\''.$obj['value'].'\'">Embed</button></td>',
                ];
                return $btns;
            }],
        ];
        return (new SSP('\App\tbl_movie', $dt))->order(0, 'desc');
```

This is my code i want to take 2 coloumn from database to 1 coloumn in datatable
e.g. title and url, vote_average and vote_count. 
What i do now is 
1. Change my 'db' to id
2. Calling Query from formatter to get the data
3. and make the return what i want from that.

**Comment by syamsoul** [comment]
You can do like this
```
// combine `title` and `url`
// combine `vote_average` and `vote_count`

$dt = [
    ['db'=>'title'],
    ['db'=>'url',          'label'=>'Title & URL',            'dt'=>0,    'formatter'=>function($obj){ return $obj['data']['title'] . "(".$obj['value'].")"; },],
    ['db'=>'vote_average'],
    ['db'=>'vote_count',   'label'=>'Vote Average & Count',   'dt'=>1,    'formatter'=>function($obj){ return $obj['data']['vote_average'] . "(".$obj['value'].")"; },],           
];
```

tell me if it's working....

**Comment by syamsoul** [comment]
wait ..i'm sorry..there's a problem.. i'm gonna fix it.... wait.. give me few minutes

**Comment by syamsoul** [comment]
> You can do like this
> 
> ```
> // combine `title` and `url`
> // combine `vote_average` and `vote_count`
> 
> $dt = [
>     ['db'=>'title'],
>     ['db'=>'url',          'label'=>'Title & URL',            'dt'=>0,    'formatter'=>function($obj){ return $obj['data']['title'] . "(".$obj['value'].")"; },],
>     ['db'=>'vote_average'],
>     ['db'=>'vote_count',   'label'=>'Vote Average & Count',   'dt'=>1,    'formatter'=>function($obj){ return $obj['data']['vote_average'] . "(".$obj['value'].")"; },],           
> ];
> ```
> tell me if it's working....

ok ...i just update...you can try it now....tell me if it's working..

**Comment by senzlord** [comment]
> You can do like this
> 
> ```
> // combine `title` and `url`
> // combine `vote_average` and `vote_count`
> 
> $dt = [
>     ['db'=>'title'],
>     ['db'=>'url',          'label'=>'Title & URL',            'dt'=>0,    'formatter'=>function($obj){ return $obj['data']['title'] . "(".$obj['value'].")"; },],
>     ['db'=>'vote_average'],
>     ['db'=>'vote_count',   'label'=>'Vote Average & Count',   'dt'=>1,    'formatter'=>function($obj){ return $obj['data']['vote_average'] . "(".$obj['value'].")"; },],           
> ];
> ```
> tell me if it's working....

It's work so well :D Thank you so much...
It much faster than what i made with taking the database again 
I Hope You Add it on README.md...

**Comment by syamsoul** [comment]
glad to hear that...
