### ISSUE TITLE
search function doesn't work in SQlite db connection

### ISSUE THREAD

**Issue by 1010shekari** [syamsoul/laravel-datatable-ssp#4]
When using SQlite db, the search function doesn't work. SQlite doesn't support the concat() and I'm getting "SQLSTATE[HY000]: General error: 1 no such function: CONCAT (SQL: SELECT count(*) AS `c` FROM (select * from (select "users"."id", ..."

**Comment by syamsoul** [comment]
Ok thanks for opening this issue... I will try to fix this ASAP...

**Comment by rickysut** [comment]
yes i have same problem with mysql.AJAX error and I fix it with replace line 202:

from : $this->filter_count = DB::select($sql_str, $sql_bindings_params)[0]->c;
to: $this->filter_count = DB::select($sql_str, [$query_search_value])[0]->c;

**Comment by syamsoul** [comment]
Latest release is now available:
https://packagist.org/packages/syamsoul/laravel-datatable-ssp#3.1.1
https://github.com/syamsoul/laravel-datatable-ssp/releases/tag/3.1.1
