### ISSUE TITLE
not working with MSSQL

### ISSUE THREAD

**Issue by gtlgaurang** [syamsoul/laravel-datatable-ssp#6]
This is my query...

> SELECT count(*) AS 
> `c` 
> FROM 
> (select * from (select [TEST].[id], [TEST].[TEST TEXT], [TEST].[TEST NUMBER], [TEST].[TEST BIT], [TEST].[TEST DATE], [TEST].[TEST BIGTEXT], [TEST].[created_at], [TEST].[updated_at] from [TEST]) as [TEST]) 
> AS `temp_count_table`

now, this query is not working in mssql.

Here **c** and **temp_count_table** qouted with  **`**  that cause the issue.

If we remove ` from keys, its working fine, like this

SELECT count(*) AS 
c 
FROM 
(select * from (select [TEST].[id], [TEST].[TEST TEXT], [TEST].[TEST NUMBER], [TEST].[TEST BIT], [TEST].[TEST DATE], [TEST].[TEST BIGTEXT], [TEST].[created_at], [TEST].[updated_at] from [TEST]) as [TEST]) 
AS temp_count_table

This query works fine

Do we have any filter function in laravel to remove ` from query ?

Regards,
Gaurang.

**Comment by syamsoul** [comment]
Latest release is now available:
https://packagist.org/packages/syamsoul/laravel-datatable-ssp#3.1.1
https://github.com/syamsoul/laravel-datatable-ssp/releases/tag/3.1.1
