### ISSUE TITLE
SQLSTATE[HY093]: Invalid parameter number

### ISSUE THREAD

**Issue by stanley-sigma** [syamsoul/laravel-datatable-ssp#8]
https://github.com/syamsoul/laravel-datatable-ssp/blob/4acaca23a71ad6cda54e4c9678c2d59c6f734404/src/SSP.php#L194

gave me the error above, I replaced with

`$query_search_value = '\'%'.$req['search']['value'].'%\'';`

**Comment by HazNet** [comment]
I have this problem too, but replacing what you said doesn't fix it!

**Comment by deepvision7** [comment]
Had to change

` 'merge_params_binding' => true,
`
to
` 'merge_params_binding' => false,
`

in the `config/sd-datatable-ssp.php`

**Comment by syamsoul** [comment]
Latest release is now available:
https://packagist.org/packages/syamsoul/laravel-datatable-ssp#3.1.1
https://github.com/syamsoul/laravel-datatable-ssp/releases/tag/3.1.1
